### ISSUE TITLE
Cypress v4.0.2 Chef install issue

### ISSUE THREAD

**Issue by oqureshi2012** [projectcypress/cypress#1149]
Good Afternoon,

I am trying to install this version of cypress using the Chef install method and when i try to run the last command to install Cypress + CVU i am getting some errors. I followed all the provided prompts. We are currently running on Ubuntu 16.04. 
See below for the beginning output and the attached image for the errors when running handlers.

sudo chef-client -z -j install_cypress_cvu.json
[2019-05-06T15:28:58-04:00] WARN: No config file found or specified on command l                                                                                                                                                             ine, using command line options.
[2019-05-06T15:28:59-04:00] INFO: Forking chef instance to converge...
Starting Chef Client, version 12.21.2
[2019-05-06T15:28:59-04:00] INFO: *** Chef 12.21.2 ***
[2019-05-06T15:28:59-04:00] INFO: Platform: x86_64-linux
[2019-05-06T15:28:59-04:00] INFO: Chef-client pid: 44744
[2019-05-06T15:28:59-04:00] INFO: The plugin path /etc/chef/ohai/plugins does no                                                                                                                                                             t exist. Skipping...
[2019-05-06T15:29:00-04:00] INFO: HTTP Request Returned 404 Not Found: Object no                                                                                                                                                             t found: chefzero://localhost:8889/nodes/DEVAZRVXCYV01
[2019-05-06T15:29:00-04:00] INFO: Setting the run_list to ["recipe[apt]", "recip                                                                                                                                                             e[cypress::default]"] from CLI options
[2019-05-06T15:29:00-04:00] INFO: Run List is [recipe[apt], recipe[cypress::defa                                                                                                                                                             ult]]
[2019-05-06T15:29:00-04:00] INFO: Run List expands to [apt, cypress::default]
[2019-05-06T15:29:00-04:00] INFO: Starting Chef Run for DEVAZRVXCYV01
[2019-05-06T15:29:00-04:00] INFO: Running start handlers
[2019-05-06T15:29:00-04:00] INFO: Start handlers complete.
[2019-05-06T15:29:00-04:00] INFO: HTTP Request Returned 404 Not Found: Object no                                                                                                                                                             t found:
resolving cookbooks for run list: ["apt", "cypress::default"]
[2019-05-06T15:29:01-04:00] INFO: Loading cookbooks [apt@6.1.4, cypress@2.0.0, e                                                                                                                                                             rlang@6.0.0, rabbitmq@5.6.3, yum-epel@3.3.0, yum-erlang_solutions@2.0.0, build-e                                                                                                                                                             ssential@8.2.1, dpkg_autostart@0.2.0, logrotate@2.2.0, seven_zip@3.1.0, mingw@2.                                                                                                                                                             1.0, windows@6.0.0]
Synchronizing Cookbooks:
[2019-05-06T15:29:01-04:00] INFO: Storing updated cookbooks/apt/recipes/default.                                                                                                                                                             rb in the cache.

![image](https://user-images.githubusercontent.com/44234194/57251503-f9dbc880-7017-11e9-86ed-3addd0b55fec.png)

**Comment by oqureshi2012** [comment]
This is the contents of chef-stacktrace.out, looks like a version mismatch??

Chef::Exceptions::CookbookChefVersionMismatch: Cookbook 'seven_zip' version '3.1.0' depends on chef version [">= 13.0"], but the running chef version is 12.21.2
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.2/lib/chef/cookbook/metadata.rb:721:in `validate_chef_version!'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.2/lib/chef/cookbook/cookbook_collection.rb:54:in `block in validate!'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.2/lib/chef/cookbook/cookbook_collection.rb:53:in `each'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.2/lib/chef/cookbook/cookbook_collection.rb:53:in `validate!'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.2/lib/chef/policy_builder/expand_node_object.rb:85:in `setup_run_context'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.2/lib/chef/client.rb:513:in `setup_run_context'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.2/lib/chef/client.rb:281:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.2/lib/chef/application.rb:295:in `block in fork_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.2/lib/chef/application.rb:283:in `fork'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.2/lib/chef/application.rb:283:in `fork_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.2/lib/chef/application.rb:248:in `block in run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.2/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.2/lib/chef/application.rb:236:in `run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.2/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.2/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.2/lib/chef/application/client.rb:450:in `loop'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.2/lib/chef/application/client.rb:450:in `interval_run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.2/lib/chef/application/client.rb:434:in `run_application'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.2/lib/chef/application.rb:59:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.2/bin/chef-client:26:in `<top (required)>'

**Comment by okeefm** [comment]
@oqureshi2012 I tried this on an Ubuntu VM and got the same result. Looks like something in the recipe has updated to require a later version of Chef. I'll talk with our DevOps folks and see if we can get versions pinned down and get this working again. Thanks for the report!

**Comment by luis1van** [comment]
@oqureshi2012 It should work for you now. Locked the package that was having problems and updated the chefdk package in the readme.

**Comment by oqureshi2012** [comment]
Thank you. Do I just re-run the Chef install step now? Or do I need to start from the beginning steps?
